issuebot:
  monitoring:
    repositories:
      - organization: spring-gradle-plugins
        name: dependency-management-plugin
        collaborators:
          - wilkinsona
      - organization: spring-gradle-plugins
        name: javadoc-plugin
        collaborators:
          - rwinch
      - organization: spring-io
        name: initializr
        collaborators:
          - bclozel
          - mbhave
          - oodamien
          - philwebb
          - snicoll
          - wilkinsona
      - organization: spring-io
        name: start.spring.io
        collaborators:
          - bclozel
          - mbhave
          - oodamien
          - philwebb
          - snicoll
          - wilkinsona
      - organization: spring-projects
        name: spring-boot
        collaborators:
          - bclozel
          - mbhave
          - philwebb
          - scottfrederick
          - snicoll
          - wilkinsona
      - organization: spring-projects
        name: spring-framework
        collaborators:
          - bclozel
          - jhoeller
          - poutsma
          - rstoyanchev
          - sbrannen
          - sdeleuze
          - snicoll
      - organization: spring-projects
        name: spring-data-bom
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-build
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-commons
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-cassandra
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-envers
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-examples
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-gemfire
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-geode
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-jdbc
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-jpa
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-keyvalue
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-ldap
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-mongodb
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-r2dbc
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-redis
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-rest
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-solr
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
      - organization: spring-projects
        name: spring-data-couchbase
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
          - daschl
          - mikereiche
          - davidkelly
      - organization: spring-projects
        name: spring-data-elasticsearch
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
          - sothawo
      - organization: spring-projects
        name: spring-data-neo4j
        collaborators:
          - christophstrobl
          - gregturn
          - mpaluch
          - jxblum
          - odrotbohm
          - schauder
          - michael-simons
          - meistermeier
      - organization: spring-projects
        name: spring-restdocs
        collaborators:
          - wilkinsona
      - organization: spring-projects
        name: spring-security
        collaborators:
          - eleftherias
          - fhanik
          - jgrandja
          - jzheaux
          - rwinch
      - organization: spring-projects
        name: spring-session
        collaborators:
          - eleftherias
          - fhanik
          - jgrandja
          - jzheaux
          - rwinch
          - vpavic
      - organization: spring-projects
        name: spring-security-oauth
        collaborators:
          - eleftherias
          - jgrandja
          - jzheaux
          - rwinch
      - organization: spring-projects-experimental
        name: spring-authorization-server
        collaborators:
          - eleftherias
          - jgrandja
          - jzheaux
          - rwinch
      - organization: spring-projects-experimental
        name: spring-native
        collaborators:
          - aclement
          - bclozel
          - christophstrobl
          - dsyer
          - eleftherias
          - fhanik
          - schauder
          - sdeleuze
          - snicoll
  triage:
    label: "status: waiting-for-triage"
  feedback:
    required_label: "status: waiting-for-feedback"
    provided_label: "status: feedback-provided"
    reminder_label: "status: feedback-reminder"
    reminder_comment: >
      If you would like us to look at this issue, please provide the requested
      information. If the information is not provided within the next 7 days this issue
      will be closed.
    close_comment: >
      Closing due to lack of requested feedback. If you would like us to look at this
      issue, please provide the requested information and we will re-open the issue.
