issuebot:
  monitoring:
    repositories:
      - organization: spring-gradle-plugins
        name: dependency-management-plugin
        collaborators:
          - wilkinsona
      - organization: spring-io
        name: initializr
        collaborators:
          - bclozel
          - mbhave
          - oodamien
          - philwebb
          - snicoll
          - wilkinsona
      - organization: spring-io
        name: start.spring.io
        collaborators:
          - bclozel
          - mbhave
          - oodamien
          - philwebb
          - snicoll
          - wilkinsona
      - organization: spring-projects
        name: spring-boot
        collaborators:
          - bclozel
          - mbhave
          - philwebb
          - scottfrederick
          - snicoll
          - wilkinsona
      - organization: spring-projects
        name: spring-framework
        collaborators:
          - bclozel
          - jhoeller
          - poutsma
          - rstoyanchev
          - sbrannen
          - sdeleuze
          - snicoll
      - organization: spring-projects
        name: spring-restdocs
        collaborators:
          - wilkinsona
      - organization: spring-projects
        name: spring-security
        collaborators:
          - eleftherias
          - fhanik
          - jgrandja
          - jzheaux
          - rwinch
      - organization: spring-projects
        name: spring-session
        collaborators:
          - eleftherias
          - fhanik
          - jgrandja
          - jzheaux
          - rwinch
          - vpavic
      - organization: spring-projects
        name: spring-security-oauth
        collaborators:
          - eleftherias
          - jgrandja
          - jzheaux
          - rwinch
  triage:
    label: "status: waiting-for-triage"
  feedback:
    required_label: "status: waiting-for-feedback"
    provided_label: "status: feedback-provided"
    reminder_label: "status: feedback-reminder"
    reminder_comment: >
      If you would like us to look at this issue, please provide the requested
      information. If the information is not provided within the next 7 days this issue
      will be closed.
    close_comment: >
      Closing due to lack of requested feedback. If you would like us to look at this
      issue, please provide the requested information and we will re-open the issue.
